On Error resume next
Public objLogFile
strPath= Wscript.ScriptFullName

Set objFSO = CreateObject("Scripting.FileSystemObject")
Set objFile = objFSO.GetFile(strPath)
strFolder = objFSO.GetParentFolderName(objFile) 
strLogFolder=objFSO.GetParentFolderName(strFolder)
strScriptPath = strLogFolder & "\Applications\GUITest2"

objFSO.DeleteFile(strLogFolder & "\Logs\*"), True
If CreateLog(objFSO,strLogFolder, strDateTime,errtxt) = False Then 
    if errtxt<>"" then
        errtxt="Run time error occured during execution. Error description generated by script is '" & errtxt & "'"
    else
        errtxt="Could not create the log, request failed"
    end if    
    objLogFile.WriteLine errtxt & vbCrLf   
    'wscript.quit
end if

    Dim qtApp
    Set qtApp = CreateObject("QuickTest.Application")
    objLogFile.WriteLine "QTP object created" & vbCrLf    
    ReqAddins = Array("web") 'take the required add ins in a array
    Var = qtApp.GetAssociatedAddinsForTest(strScriptPath) 'returns an array of loaded add ins
    changeaddin = False
    For Each testaddin In Var
            If qtApp.AddIns(testaddin).Status <> "active" Then 'check status of loaded addins(checked or not) for the current test
                changeaddin = True
                Exit For
            End If
    Next
    If qtApp.Launched And changeaddin Then
             qtApp.Quit ' If a change is necessary, exit QuickTest to modify the loaded add-ins
    End If
    If changeaddin Then
            activeok = qtApp.SetActiveAddins(ReqAddins, errordescription) 'Here load the required addins from the array it returns true if addins loaded sucesfully, false if not
            If Not activeok Then
                   strMsg= "Not able to load the addins" & ": " & errordescription
            objLogFile.WriteLine strMsg & vbCrLf                   
                   Set qtApp = Nothing  
            End If
    End If
    qtApp.LAUNCH
    objLogFile.WriteLine "QTP launched successfully" & vbCrLf                   
    qtApp.Visible = True
    qtApp.Open strScriptPath
    objLogFile.WriteLine "QTP script opened" & vbCrLf                   

    Set directoryTestRun = qtApp.Test
	directoryTestRun.Run
strMsg="QTP script has been executed successfully"
    objLogFile.WriteLine strMsg & vbCrLf 
    TaskKill = CreateObject("WScript.Shell").Run("taskkill /f /im " & "UFT.EXE", 0, True)
    TaskKill = CreateObject("WScript.Shell").Run("taskkill /f /im " & "QtpAutomationAgent.exe", 0, True)
    objLogFile.WriteLine "Killed UFT Process" & vbCrLf 
set objLogFile=Nothing
Set qtApp=nothing

Function CreateLog(objFSO,strLogFolder, strDateTime,errtxt)
    On Error Resume Next    
    CreateLog = True
    sErrMessage = ""     
    strLogFileName = strLogFolder & "\Logs\" & "DriverLog" & strDateTime & ".txt"
    Set objLogFile = objFSO.CreateTextFile(strLogFileName, True)
    objLogFile.WriteLine "Log File Created Successfully" & vbCrLf
    If Err.Number <> 0 Then
        sErrMessage = Err.Description
    errtxt="Log File Creation Failed due to error '" & sErrMessage & "'"
        CreateLog = False
        objLogFile.WriteLine errtxt & vbCrLf
        Err.Clear
        On Error GoTo 0
    End If
End Function